BRANCH=master
RESULTS=
ARCH=x86_64
GIT_DESCRIBE=v5.5-rc1-12-g6794862a16ef
API=
PUBLISH=false
TREE_NAME=mainline
EMAIL=false
#
BUILD_DISPLAY_NAME=#819
BUILD_ID=819
BUILD_NUMBER=819
BUILD_TAG=jenkins-kernel-arch-complete-819
BUILD_URL=http://ci.staging.lkft.org/job/kernel-arch-complete/819/
EXECUTOR_NUMBER=1
#HOME=/home/ubuntu
#HUDSON_COOKIE=4b129cdb-43f8-4ad2-b3a1-0d337061cedf
#HUDSON_HOME=/var/jenkins_home
#HUDSON_SERVER_COOKIE=b3643c74f0aa7bc5
HUDSON_URL=http://ci.staging.lkft.org/
#JENKINS_HOME=/var/jenkins_home
#JENKINS_SERVER_COOKIE=b3643c74f0aa7bc5
JENKINS_URL=http://ci.staging.lkft.org/
JOB_BASE_NAME=kernel-arch-complete
JOB_DISPLAY_URL=http://ci.staging.lkft.org/job/kernel-arch-complete/display/redirect
JOB_NAME=kernel-arch-complete
JOB_URL=http://ci.staging.lkft.org/job/kernel-arch-complete/
LANG=C.UTF-8
LOGNAME=ubuntu
#MAIL=/var/mail/ubuntu
NODE_LABELS="build-trigger ci.staging.lkft.org docker monitor"
NODE_NAME=ci.staging.lkft.org
#OLDPWD=/home/ubuntu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/workspace/workspace/kernel-arch-complete
QA_REPORTS_TOKEN=****
RUN_CHANGES_DISPLAY_URL=http://ci.staging.lkft.org/job/kernel-arch-complete/819/display/redirect?page=changes
RUN_DISPLAY_URL=http://ci.staging.lkft.org/job/kernel-arch-complete/819/display/redirect
#SHELL=/bin/bash
#SHLVL=2
#SSH_CLIENT=172.17.0.2 41620 22
#SSH_CONNECTION=172.17.0.2 41620 172.31.43.249 22
#USER=ubuntu
WORKSPACE="$(dirname "$(readlink -e $0)")"/workspace
#XDG_RUNTIME_DIR=/run/user/1000
#XDG_SESSION_ID=1
